"""empty message

Revision ID: 16aae8d265e1
Revises: 
Create Date: 2018-12-20 01:34:31.953517

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '16aae8d265e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.Text(), nullable=True),
                    sa.Column('revision_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('page',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('revision_latest', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_page_title'), 'page', ['title'], unique=True)
    op.create_table('revision',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('page_id', sa.Integer(), nullable=True),
                    sa.Column('content_id', sa.Integer(), nullable=True),
                    sa.Column('actual', sa.Boolean(), nullable=True),
                    sa.Column('add_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revision')
    op.drop_index(op.f('ix_page_title'), table_name='page')
    op.drop_table('page')
    op.drop_table('content')
    # ### end Alembic commands ###
