"""empty message

Revision ID: 6dd3f036ec3e
Revises: 16aae8d265e1
Create Date: 2018-12-20 01:39:59.110229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd3f036ec3e'
down_revision = '16aae8d265e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'content', 'revision', ['revision_id'], ['id'])
    op.create_foreign_key(None, 'revision', 'content', ['content_id'], ['id'])
    op.create_foreign_key(None, 'revision', 'page', ['page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revision', type_='foreignkey')
    op.drop_constraint(None, 'revision', type_='foreignkey')
    op.drop_constraint(None, 'content', type_='foreignkey')
    # ### end Alembic commands ###
